// This document is auto generated!
export const PermissionsTable = {
	HelpDesk_Tickets_Read: "helpdesk.tickets.read",
	HelpDesk_Tickets_Write: "helpdesk.tickets.write",
	HelpDesk_Tickets_All_Read: "helpdesk.tickets.all.read",
	HelpDesk_Tickets_Company_Write: "helpdesk.tickets.company.write",
	HelpDesk_TicketWork_Read: "helpdesk.tickets.work.read",
	HelpDesk_TicketWork_InternalRead: "helpdesk.tickets.work.internal.read",
	HelpDesk_TicketWork_Write: "helpdesk.tickets.work.write",
	HelpDesk_TicketConversation_Read: "helpdesk.tickets.conversation.read",
	HelpDesk_TicketConversation_Write: "helpdesk.tickets.conversation.write",
	HelpDesk_Tags_Read: "helpdesk.tags.read",
	HelpDesk_Tags_Write: "helpdesk.tags.write",
	HelpDesk_Categories_Read: "helpdesk.categories.read",
	HelpDesk_Categories_Write: "helpdesk.categories.write",
	HelpDesk_Priorities_Read: "helpdesk.priorities.read",
	HelpDesk_Priorities_Write: "helpdesk.priorities.write",
	HelpDesk_Statistics_Read: "helpdesk.statistics.read",
	Other: 1234,
}
